name: Generate Dev Documentation
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Generate docs
      run: npm run docs
    - name: Push docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        external_repository: HackIllinois/adonix-dev-docs
        publish_branch: master
        publish_dir: ./docs/
        
